In [ ]:
#1.Write a Python program to compute the eigenvalues and right eigenvectors of a given square array.

In [4]:
# eigendecomposition
from numpy import array
from numpy.linalg import eig
#define matrix
A = array([
    [5, 9, 8],
    [7, 4, 5],
    [6, 2, 3]])
print(A)
#computing eigvalues, eigvectors
values, vectors = eig(A)
print(values)
print(vectors)


[[5 9 8]
 [7 4 5]
 [6 2 3]]
[16.51978461 -4.36731846 -0.15246615]
[[-0.72064652 -0.77477757 -0.22326377]
 [-0.56396831  0.32361316 -0.57307478]
 [-0.40324723  0.54313372  0.78850401]]


In [5]:
#confirming first eigenvector
B = A.dot(vectors[:, 0])
print(B)
C = vectors[:, 0] * values[0]
print(C)

[-11.90492531  -9.31663508  -6.66155746]
[-11.90492531  -9.31663508  -6.66155746]


In [6]:
#2. Write a Python program to compute the factor of a given array by Singular Value Decomposition

In [11]:
# singular-value decomposition
import scipy
from numpy import array
from scipy.linalg import svd
# define a matrix
A = array([
[5, 7],
[2, 4],
[3, 8]])
print(A)
# factorize
U, s, V = svd(A)
print(U)
print(s)
print(V)

[[5 7]
 [2 4]
 [3 8]]
[[-0.66479374  0.72063053  0.19682713]
 [-0.34859945 -0.06623    -0.93492888]
 [-0.66070243 -0.6901487   0.2952407 ]]
[12.82533418  1.58455142]
[[-0.46807941 -0.8836864 ]
 [ 0.8836864  -0.46807941]]


In [12]:
# Reconstructing the matrix to double check.
from numpy import array
from numpy import diag
from numpy import zeros
from scipy.linalg import svd
# define matrix
A = array([
[5, 7],
[2, 4],
[3, 8]])
print(A)
# factorize
U, s, V = svd(A)
# create m x n Sigma matrix
Sigma = zeros((A.shape[0], A.shape[1]))
# populate Sigma with n x n diagonal matrix
Sigma[:A.shape[1], :A.shape[1]] = diag(s)
# reconstruct matrix
B = U.dot(Sigma.dot(V))
print(B)

[[5 7]
 [2 4]
 [3 8]]
[[5. 7.]
 [2. 4.]
 [3. 8.]]


In [13]:
#3. Write a Python program to compute the determinant of an array.

In [15]:
import numpy as np
from numpy.linalg import det
A = np.array([
    [3, 6, 7],
    [5, 3, 2],
    [2, 8, 9]])
#determinant of array
B = det(A)
B

25.00000000000004